version: '3'
services:
  discovery-service:
    container_name: discovery-service
    build:
      context: ../DiscoveryService
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
    entrypoint: [ "sh", "-c", "sleep 5; java -jar app.jar" ]

  vault:
    container_name: vault
    image: hashicorp/vault:latest
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    volumes:
      - ./vault/data:/vault/data
      - ./vault/config:/vault/config
      - ./vault/vault-startup.sh:/app/vault-startup.sh
    command: "sh /app/vault-startup.sh"
    networks:
      - spring-cloud-network

  auth-service:
    container_name: auth-service
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
    entrypoint: [ "sh", "-c", "sleep 5; java -jar app.jar" ]

  auth-service-postgres:
    container_name: auth-service-postgres
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: auth-service
    networks:
      - spring-cloud-network
    volumes:
      - auth-service-postgres-data:/var/lib/postgresql/data
      
  details-service:
    container_name: details-service
    build:
      context: ../DetailsService
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
    entrypoint: [ "sh", "-c", "sleep 5; java -jar app.jar" ]

  details-service-postgres:
    container_name: details-service-postgres
    image: postgres:17.2
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: details-service
      PGPORT: 5433
    networks:
      - spring-cloud-network
    volumes:
      - details-service-postgres-data:/var/lib/postgresql/data

  payment-service:
    container_name: payment-service
    build:
      context: ../PaymentService
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
    entrypoint: [ "sh", "-c", "sleep 5; java -jar app.jar" ]

  payment-service-postgres:
    container_name: payment-service-postgres
    image: postgres:17.2
    ports:
      - 5435:5435
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: payment-service
      PGPORT: 5435
    networks:
      - spring-cloud-network
    volumes:
      - payment-service-postgres-data:/var/lib/postgresql/data

  gateway:
    container_name: gateway
    build:
      context: ../Gateway
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - spring-cloud-network
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
    entrypoint: [ "sh", "-c", "sleep 5; java -jar app.jar" ]

  broker:
    image: confluentinc/cp-kafka:4.0.0
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spring-cloud-network
    depends_on:
      - zookeeper
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

volumes:
  auth-service-postgres-data: {}
  details-service-postgres-data: {}
  payment-service-postgres-data: {}