version: '3'
services:
  discovery-service:
    container_name: discovery-service
    build:
      context: ../DiscoveryService
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
    depends_on:
      - config-service
    entrypoint: [ "sh", "-c", "sleep 5; java -jar app.jar" ]

  config-service:
    container_name: config-service
    build:
      context: ../ConfigService
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network
  auth-service:
    container_name: auth-service
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    depends_on:
      - config-service
    entrypoint: [ "sh", "-c", "sleep 5; java -jar app.jar" ]

  auth-service-postgres:
    container_name: auth-service-postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: auth-service
    networks:
      - spring-cloud-network
    volumes:
      - auth-service-postgres-data:/var/lib/postgresql/data
networks:
  spring-cloud-network:
    driver: bridge

volumes:
  auth-service-postgres-data: